<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15153" started-at="2017-11-07T15:18:30Z" finished-at="2017-11-07T15:18:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15153" started-at="2017-11-07T15:18:30Z" finished-at="2017-11-07T15:18:45Z">
      <class name="com.vaticahealth.vatica.testcases.SmokeTest">
        <test-method status="PASS" signature="invokeUrl()[pri:0, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26]" name="invokeUrl" is-config="true" duration-ms="13" started-at="2017-11-07T20:48:29Z" finished-at="2017-11-07T20:48:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invokeUrl -->
        <test-method status="PASS" signature="startReport()[pri:0, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26]" name="startReport" is-config="true" duration-ms="497" started-at="2017-11-07T20:48:29Z" finished-at="2017-11-07T20:48:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="setUpBeforeEveryTest()[pri:0, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26]" name="setUpBeforeEveryTest" is-config="true" duration-ms="1" started-at="2017-11-07T20:48:30Z" finished-at="2017-11-07T20:48:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeEveryTest -->
        <test-method status="FAIL" signature="homePage_VerifyHomeCategories()[pri:2, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26]" name="homePage_VerifyHomeCategories" duration-ms="15106" started-at="2017-11-07T20:48:30Z" finished-at="2017-11-07T20:48:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [Action World]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [Action World]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.vaticahealth.vatica.testcases.SmokeTest.homePage_VerifyHomeCategories(SmokeTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePage_VerifyHomeCategories -->
        <test-method status="FAIL" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26]" name="getResult" is-config="true" duration-ms="5" started-at="2017-11-07T20:48:45Z" finished-at="2017-11-07T20:48:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=homePage_VerifyHomeCategories status=FAILURE method=SmokeTest.homePage_VerifyHomeCategories()[pri:2, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.vaticahealth.vatica.config.TestAnnotation.getResult(TestAnnotation.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:731)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="endReport()[pri:0, instance:com.vaticahealth.vatica.testcases.SmokeTest@6253c26]" name="endReport" is-config="true" duration-ms="0" started-at="2017-11-07T20:48:45Z" finished-at="2017-11-07T20:48:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.vaticahealth.vatica.testcases.SmokeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
